//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeilWebTranslations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VeilWebTranslations.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETAILS.
        /// </summary>
        public static string About_Details {
            get {
                return ResourceManager.GetString("About_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All images used with permission of the.
        /// </summary>
        public static string About_DetailsText1 {
            get {
                return ResourceManager.GetString("About_DetailsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price information provided by CoinGecko.
        /// </summary>
        public static string About_DetailsText2 {
            get {
                return ResourceManager.GetString("About_DetailsText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool information provided from each pool&apos;s API.
        /// </summary>
        public static string About_DetailsText3 {
            get {
                return ResourceManager.GetString("About_DetailsText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENJOY!.
        /// </summary>
        public static string About_Enjoy {
            get {
                return ResourceManager.GetString("About_Enjoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUGGESTIONS?.
        /// </summary>
        public static string About_Suggestion {
            get {
                return ResourceManager.GetString("About_Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell me! codeofalltrades@outlook.com.
        /// </summary>
        public static string About_SuggestionText {
            get {
                return ResourceManager.GetString("About_SuggestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHY?.
        /// </summary>
        public static string About_Why {
            get {
                return ResourceManager.GetString("About_Why", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The website was built to provide graphical information on the Veil network..
        /// </summary>
        public static string About_WhyReason {
            get {
                return ResourceManager.GetString("About_WhyReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/2 Day MA.
        /// </summary>
        public static string Charts_0_5DayMA {
            get {
                return ResourceManager.GetString("Charts_0.5DayMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180 Days.
        /// </summary>
        public static string Charts_180Days {
            get {
                return ResourceManager.GetString("Charts_180Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Day MA.
        /// </summary>
        public static string Charts_1DayMA {
            get {
                return ResourceManager.GetString("Charts_1DayMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 Days.
        /// </summary>
        public static string Charts_30Days {
            get {
                return ResourceManager.GetString("Charts_30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Day MA.
        /// </summary>
        public static string Charts_3DayMA {
            get {
                return ResourceManager.GetString("Charts_3DayMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Days.
        /// </summary>
        public static string Charts_3Days {
            get {
                return ResourceManager.GetString("Charts_3Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 Days.
        /// </summary>
        public static string Charts_60Days {
            get {
                return ResourceManager.GetString("Charts_60Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90 Days.
        /// </summary>
        public static string Charts_90Days {
            get {
                return ResourceManager.GetString("Charts_90Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Charts_Block {
            get {
                return ResourceManager.GetString("Charts_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated:.
        /// </summary>
        public static string Charts_LastUpdated {
            get {
                return ResourceManager.GetString("Charts_LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        public static string Charts_Live {
            get {
                return ResourceManager.GetString("Charts_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collections of charts detailing Veil network information.
        /// </summary>
        public static string Charts_MetaDescription {
            get {
                return ResourceManager.GetString("Charts_MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONEY SUPPLY.
        /// </summary>
        public static string Charts_MoneySupply {
            get {
                return ResourceManager.GetString("Charts_MoneySupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoS BLOCKS.
        /// </summary>
        public static string Charts_PosBlocks {
            get {
                return ResourceManager.GetString("Charts_PosBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoS Blocks (24h).
        /// </summary>
        public static string Charts_PosBlocks24hr {
            get {
                return ResourceManager.GetString("Charts_PosBlocks24hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoS Difficulty.
        /// </summary>
        public static string Charts_PosDifficulty {
            get {
                return ResourceManager.GetString("Charts_PosDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoW BLOCKS.
        /// </summary>
        public static string Charts_PowBlocks {
            get {
                return ResourceManager.GetString("Charts_PowBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoW Blocks (24h).
        /// </summary>
        public static string Charts_PowBlocks24hr {
            get {
                return ResourceManager.GetString("Charts_PowBlocks24hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoW Difficulty.
        /// </summary>
        public static string Charts_PowDifficulty {
            get {
                return ResourceManager.GetString("Charts_PowDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoS/PoW SPLIT - COUNT.
        /// </summary>
        public static string Charts_PowPosSplitCount {
            get {
                return ResourceManager.GetString("Charts_PowPosSplitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoS/PoW SPLIT - PERCENT.
        /// </summary>
        public static string Charts_PowPosSplitPercent {
            get {
                return ResourceManager.GetString("Charts_PowPosSplitPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Chart -&gt; Click or Touch + Drag!.
        /// </summary>
        public static string Charts_ZoomChart {
            get {
                return ResourceManager.GetString("Charts_ZoomChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency.
        /// </summary>
        public static string DenomEfficiency_Efficiency {
            get {
                return ResourceManager.GetString("DenomEfficiency_Efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated:.
        /// </summary>
        public static string DenomEfficiency_LastUpdated {
            get {
                return ResourceManager.GetString("DenomEfficiency_LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoS Reward Snapshot - A current view of denom staking performance.
        /// </summary>
        public static string DenomEfficiency_MetaDescription {
            get {
                return ResourceManager.GetString("DenomEfficiency_MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoS Reward Snapshot.
        /// </summary>
        public static string DenomEfficiency_MetaTitle {
            get {
                return ResourceManager.GetString("DenomEfficiency_MetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward distribution.
        /// </summary>
        public static string DenomEfficiency_RewardDistribution {
            get {
                return ResourceManager.GetString("DenomEfficiency_RewardDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoS REWARD SNAPSHOT - 24 Hours.
        /// </summary>
        public static string DenomEfficiency_RewardSnapShot24hr {
            get {
                return ResourceManager.GetString("DenomEfficiency_RewardSnapShot24hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoS REWARD SNAPSHOT - 3 Days.
        /// </summary>
        public static string DenomEfficiency_RewardSnapShot3Day {
            get {
                return ResourceManager.GetString("DenomEfficiency_RewardSnapShot3Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoS REWARD SNAPSHOT - 7 Days.
        /// </summary>
        public static string DenomEfficiency_RewardSnapShot7Day {
            get {
                return ResourceManager.GetString("DenomEfficiency_RewardSnapShot7Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply distribution.
        /// </summary>
        public static string DenomEfficiency_SupplyDistribution {
            get {
                return ResourceManager.GetString("DenomEfficiency_SupplyDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24hr diff avg.
        /// </summary>
        public static string MiningCalc_24hrDiffAvg {
            get {
                return ResourceManager.GetString("MiningCalc_24hrDiffAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block reward.
        /// </summary>
        public static string MiningCalc_BlockReward {
            get {
                return ResourceManager.GetString("MiningCalc_BlockReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTC value.
        /// </summary>
        public static string MiningCalc_BtcValue {
            get {
                return ResourceManager.GetString("MiningCalc_BtcValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calculate.
        /// </summary>
        public static string MiningCalc_Calculate {
            get {
                return ResourceManager.GetString("MiningCalc_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constants.
        /// </summary>
        public static string MiningCalc_Constants {
            get {
                return ResourceManager.GetString("MiningCalc_Constants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string MiningCalc_Cost {
            get {
                return ResourceManager.GetString("MiningCalc_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string MiningCalc_Day {
            get {
                return ResourceManager.GetString("MiningCalc_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string MiningCalc_Difficulty {
            get {
                return ResourceManager.GetString("MiningCalc_Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Rewards.
        /// </summary>
        public static string MiningCalc_EstimatedRewards {
            get {
                return ResourceManager.GetString("MiningCalc_EstimatedRewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est. Rewards.
        /// </summary>
        public static string MiningCalc_EstRewards {
            get {
                return ResourceManager.GetString("MiningCalc_EstRewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange rate.
        /// </summary>
        public static string MiningCalc_ExchangeRate {
            get {
                return ResourceManager.GetString("MiningCalc_ExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fees.
        /// </summary>
        public static string MiningCalc_Fees {
            get {
                return ResourceManager.GetString("MiningCalc_Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash rate.
        /// </summary>
        public static string MiningCalc_Hashrate {
            get {
                return ResourceManager.GetString("MiningCalc_Hashrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hash rate per coin.
        /// </summary>
        public static string MiningCalc_HashRatePerCoin {
            get {
                return ResourceManager.GetString("MiningCalc_HashRatePerCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string MiningCalc_Hour {
            get {
                return ResourceManager.GetString("MiningCalc_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string MiningCalc_Month {
            get {
                return ResourceManager.GetString("MiningCalc_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This calculator is supplied with real reward data to increase accuracy..
        /// </summary>
        public static string MiningCalc_PageSubTitle {
            get {
                return ResourceManager.GetString("MiningCalc_PageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mining Calculator.
        /// </summary>
        public static string MiningCalc_PageTitle {
            get {
                return ResourceManager.GetString("MiningCalc_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per.
        /// </summary>
        public static string MiningCalc_Per {
            get {
                return ResourceManager.GetString("MiningCalc_Per", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string MiningCalc_Power {
            get {
                return ResourceManager.GetString("MiningCalc_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Cost.
        /// </summary>
        public static string MiningCalc_PowerCost {
            get {
                return ResourceManager.GetString("MiningCalc_PowerCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit.
        /// </summary>
        public static string MiningCalc_Profit {
            get {
                return ResourceManager.GetString("MiningCalc_Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset.
        /// </summary>
        public static string MiningCalc_Reset {
            get {
                return ResourceManager.GetString("MiningCalc_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rev. BTC.
        /// </summary>
        public static string MiningCalc_RevBtc {
            get {
                return ResourceManager.GetString("MiningCalc_RevBtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rev. $.
        /// </summary>
        public static string MiningCalc_RevDollar {
            get {
                return ResourceManager.GetString("MiningCalc_RevDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hash rate required for 24 hours to generate 1 Veil..
        /// </summary>
        public static string MiningCalc_Tooltip1 {
            get {
                return ResourceManager.GetString("MiningCalc_Tooltip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24hr average hash rate.
        /// </summary>
        public static string MiningCalc_Tooltip2 {
            get {
                return ResourceManager.GetString("MiningCalc_Tooltip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to divided by.
        /// </summary>
        public static string MiningCalc_Tooltip3 {
            get {
                return ResourceManager.GetString("MiningCalc_Tooltip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 hr reward total.
        /// </summary>
        public static string MiningCalc_Tooltip4 {
            get {
                return ResourceManager.GetString("MiningCalc_Tooltip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equals.
        /// </summary>
        public static string MiningCalc_Tooltip5 {
            get {
                return ResourceManager.GetString("MiningCalc_Tooltip5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hash rate per coin.
        /// </summary>
        public static string MiningCalc_Tooltip6 {
            get {
                return ResourceManager.GetString("MiningCalc_Tooltip6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string MiningCalc_Week {
            get {
                return ResourceManager.GetString("MiningCalc_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string MiningCalc_Year {
            get {
                return ResourceManager.GetString("MiningCalc_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation.
        /// </summary>
        public static string NavMenu_Calculation {
            get {
                return ResourceManager.GetString("NavMenu_Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string NavMenu_Charts {
            get {
                return ResourceManager.GetString("NavMenu_Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution.
        /// </summary>
        public static string NavMenu_Distribution {
            get {
                return ResourceManager.GetString("NavMenu_Distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mining Calculator.
        /// </summary>
        public static string NavMenu_MiningCalculator {
            get {
                return ResourceManager.GetString("NavMenu_MiningCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mining Pools.
        /// </summary>
        public static string NavMenu_MiningPools {
            get {
                return ResourceManager.GetString("NavMenu_MiningPools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Time.
        /// </summary>
        public static string NavMenu_RealTime {
            get {
                return ResourceManager.GetString("NavMenu_RealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot.
        /// </summary>
        public static string NavMenu_Snapshot {
            get {
                return ResourceManager.GetString("NavMenu_Snapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staking.
        /// </summary>
        public static string NavMenu_Staking {
            get {
                return ResourceManager.GetString("NavMenu_Staking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        public static string NavMenu_Stats {
            get {
                return ResourceManager.GetString("NavMenu_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string NavMenu_Transactions {
            get {
                return ResourceManager.GetString("NavMenu_Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 Days.
        /// </summary>
        public static string Pow_30Days {
            get {
                return ResourceManager.GetString("Pow_30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Days.
        /// </summary>
        public static string Pow_3Days {
            get {
                return ResourceManager.GetString("Pow_3Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 Days.
        /// </summary>
        public static string Pow_60Days {
            get {
                return ResourceManager.GetString("Pow_60Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90 Days.
        /// </summary>
        public static string Pow_90Days {
            get {
                return ResourceManager.GetString("Pow_90Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT BLOCK.
        /// </summary>
        public static string Pow_CurrentBlock {
            get {
                return ResourceManager.GetString("Pow_CurrentBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLOBAL HASH.
        /// </summary>
        public static string Pow_GlobalHash {
            get {
                return ResourceManager.GetString("Pow_GlobalHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated:.
        /// </summary>
        public static string Pow_LastUpdated {
            get {
                return ResourceManager.GetString("Pow_LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veil network and mining pool information.
        /// </summary>
        public static string Pow_MetaDescription {
            get {
                return ResourceManager.GetString("Pow_MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mining Pools.
        /// </summary>
        public static string Pow_MiningPools {
            get {
                return ResourceManager.GetString("Pow_MiningPools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string Pow_Network {
            get {
                return ResourceManager.GetString("Pow_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POOL HASH.
        /// </summary>
        public static string Pow_PoolHash {
            get {
                return ResourceManager.GetString("Pow_PoolHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POOL WORKERS.
        /// </summary>
        public static string Pow_PoolWorkers {
            get {
                return ResourceManager.GetString("Pow_PoolWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoW DIFF.
        /// </summary>
        public static string Pow_PowDiff {
            get {
                return ResourceManager.GetString("Pow_PowDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoW DIFFICULTY.
        /// </summary>
        public static string Pow_PowDifficulty {
            get {
                return ResourceManager.GetString("Pow_PowDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN HASH.
        /// </summary>
        public static string Pow_UnknownHash {
            get {
                return ResourceManager.GetString("Pow_UnknownHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workers.
        /// </summary>
        public static string Pow_Workers {
            get {
                return ResourceManager.GetString("Pow_Workers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Chart -&gt; Click or Touch + Drag!.
        /// </summary>
        public static string Pow_ZoomChart {
            get {
                return ResourceManager.GetString("Pow_ZoomChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string RealTime_About {
            get {
                return ResourceManager.GetString("RealTime_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to built by.
        /// </summary>
        public static string RealTime_BuiltBy {
            get {
                return ResourceManager.GetString("RealTime_BuiltBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 24 Hours.
        /// </summary>
        public static string RealTime_Last24Hours {
            get {
                return ResourceManager.GetString("RealTime_Last24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAST BLOCK.
        /// </summary>
        public static string RealTime_LastBlock {
            get {
                return ResourceManager.GetString("RealTime_LastBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for more... Check out the Charts page!.
        /// </summary>
        public static string RealTime_LookingForMore {
            get {
                return ResourceManager.GetString("RealTime_LookingForMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Stats.
        /// </summary>
        public static string RealTime_MainHeading {
            get {
                return ResourceManager.GetString("RealTime_MainHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to real-time data.
        /// </summary>
        public static string RealTime_MainSubHeading {
            get {
                return ResourceManager.GetString("RealTime_MainSubHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Price.
        /// </summary>
        public static string RealTime_MarketPrice {
            get {
                return ResourceManager.GetString("RealTime_MarketPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veil Stats - visualize the Veil network information.
        /// </summary>
        public static string RealTime_MetaDescription {
            get {
                return ResourceManager.GetString("RealTime_MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-Time Data.
        /// </summary>
        public static string RealTime_MetaTitle {
            get {
                return ResourceManager.GetString("RealTime_MetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other.
        /// </summary>
        public static string RealTime_Other {
            get {
                return ResourceManager.GetString("RealTime_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoS BLOCKS.
        /// </summary>
        public static string RealTime_PosBlocks {
            get {
                return ResourceManager.GetString("RealTime_PosBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoS DIFF.
        /// </summary>
        public static string RealTime_PosDiff {
            get {
                return ResourceManager.GetString("RealTime_PosDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoW BLOCKS.
        /// </summary>
        public static string RealTime_PowBlocks {
            get {
                return ResourceManager.GetString("RealTime_PowBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoW DIFF.
        /// </summary>
        public static string RealTime_PowDiff {
            get {
                return ResourceManager.GetString("RealTime_PowDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total All-Time.
        /// </summary>
        public static string RealTime_TotalAllTime {
            get {
                return ResourceManager.GetString("RealTime_TotalAllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veil Budget Excess.
        /// </summary>
        public static string RealTime_VeilBudgetExcess {
            get {
                return ResourceManager.GetString("RealTime_VeilBudgetExcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veil Foundation.
        /// </summary>
        public static string RealTime_VeilFoundation {
            get {
                return ResourceManager.GetString("RealTime_VeilFoundation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEIL SUPPLY.
        /// </summary>
        public static string RealTime_VeilSupply {
            get {
                return ResourceManager.GetString("RealTime_VeilSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zerocoin.
        /// </summary>
        public static string RealTime_Zerocoin {
            get {
                return ResourceManager.GetString("RealTime_Zerocoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZEROCOIN SUPPLY.
        /// </summary>
        public static string RealTime_ZeroCoinSupply {
            get {
                return ResourceManager.GetString("RealTime_ZeroCoinSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/2 Day MA.
        /// </summary>
        public static string Script_0_5DayMA {
            get {
                return ResourceManager.GetString("Script_0_5DayMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Day MA.
        /// </summary>
        public static string Script_1DayMA {
            get {
                return ResourceManager.GetString("Script_1DayMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Day MA.
        /// </summary>
        public static string Script_3DayMA {
            get {
                return ResourceManager.GetString("Script_3DayMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 Day MA.
        /// </summary>
        public static string Script_7DayMA {
            get {
                return ResourceManager.GetString("Script_7DayMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Script_Block {
            get {
                return ResourceManager.GetString("Script_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Transactions.
        /// </summary>
        public static string Script_DailyTransactions {
            get {
                return ResourceManager.GetString("Script_DailyTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string Script_Difficulty {
            get {
                return ResourceManager.GetString("Script_Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency.
        /// </summary>
        public static string Script_Efficiency {
            get {
                return ResourceManager.GetString("Script_Efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        public static string Script_Live {
            get {
                return ResourceManager.GetString("Script_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoS Blocks.
        /// </summary>
        public static string Script_PosBlocks {
            get {
                return ResourceManager.GetString("Script_PosBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoW Blocks.
        /// </summary>
        public static string Script_PowBlocks {
            get {
                return ResourceManager.GetString("Script_PowBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoS/PoW SPLIT.
        /// </summary>
        public static string Script_PowPosSplit {
            get {
                return ResourceManager.GetString("Script_PowPosSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward Distribution.
        /// </summary>
        public static string Script_RewardDistribution {
            get {
                return ResourceManager.GetString("Script_RewardDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply Distribution.
        /// </summary>
        public static string Script_SupplyDistribution {
            get {
                return ResourceManager.GetString("Script_SupplyDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Supply.
        /// </summary>
        public static string Script_TotalSupply {
            get {
                return ResourceManager.GetString("Script_TotalSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string Script_Transactions {
            get {
                return ResourceManager.GetString("Script_Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Day MA.
        /// </summary>
        public static string StakeDistribution_1DayMA {
            get {
                return ResourceManager.GetString("StakeDistribution_1DayMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Day MA.
        /// </summary>
        public static string StakeDistribution_3DayMA {
            get {
                return ResourceManager.GetString("StakeDistribution_3DayMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 Day MA.
        /// </summary>
        public static string StakeDistribution_7DayMA {
            get {
                return ResourceManager.GetString("StakeDistribution_7DayMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you believe these calculations are incorrect please let me know!.
        /// </summary>
        public static string StakeDistribution_CalculationIncorrect {
            get {
                return ResourceManager.GetString("StakeDistribution_CalculationIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoS REWARD DISTRIBUTION - 3 Days.
        /// </summary>
        public static string StakeDistribution_ChartTitle {
            get {
                return ResourceManager.GetString("StakeDistribution_ChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denom Conversion Rate = Number of Blocks Staked by Denom / Number of PoS Blocks.
        /// </summary>
        public static string StakeDistribution_DenomConversionFn {
            get {
                return ResourceManager.GetString("StakeDistribution_DenomConversionFn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denom Conversion Rate.
        /// </summary>
        public static string StakeDistribution_DenomConversionRate {
            get {
                return ResourceManager.GetString("StakeDistribution_DenomConversionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denom Efficiency.
        /// </summary>
        public static string StakeDistribution_DenomEfficiency {
            get {
                return ResourceManager.GetString("StakeDistribution_DenomEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denom Efficiency = (Denom Conversion Rate / Denom Percentage Supply) * 100.
        /// </summary>
        public static string StakeDistribution_DenomEfficiencyFn {
            get {
                return ResourceManager.GetString("StakeDistribution_DenomEfficiencyFn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denom Percentage Supply.
        /// </summary>
        public static string StakeDistribution_DenomPercentageSupply {
            get {
                return ResourceManager.GetString("StakeDistribution_DenomPercentageSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denom Conversion Rate = Number of Blocks Staked by Denom / Number of PoS Blocks.
        /// </summary>
        public static string StakeDistribution_DenomPercentFn {
            get {
                return ResourceManager.GetString("StakeDistribution_DenomPercentFn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denom Supply.
        /// </summary>
        public static string StakeDistribution_DenomSupply {
            get {
                return ResourceManager.GetString("StakeDistribution_DenomSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denom Supply = Average denom supply over the last X blocks.
        /// </summary>
        public static string StakeDistribution_DenomSupplyFn {
            get {
                return ResourceManager.GetString("StakeDistribution_DenomSupplyFn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the denom to toggle the series.
        /// </summary>
        public static string StakeDistribution_DenomToggle {
            get {
                return ResourceManager.GetString("StakeDistribution_DenomToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFFICIENCY CALCULATION.
        /// </summary>
        public static string StakeDistribution_EfficiencyCalculation {
            get {
                return ResourceManager.GetString("StakeDistribution_EfficiencyCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How is this calculated?.
        /// </summary>
        public static string StakeDistribution_HowCalculated {
            get {
                return ResourceManager.GetString("StakeDistribution_HowCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated:.
        /// </summary>
        public static string StakeDistribution_LastUpdated {
            get {
                return ResourceManager.GetString("StakeDistribution_LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Day = 1440 Blocks.
        /// </summary>
        public static string StakeDistribution_MA1Day {
            get {
                return ResourceManager.GetString("StakeDistribution_MA1Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Day = 4320 Blocks.
        /// </summary>
        public static string StakeDistribution_MA3Day {
            get {
                return ResourceManager.GetString("StakeDistribution_MA3Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 Day = 10080 Blocks.
        /// </summary>
        public static string StakeDistribution_MA7Day {
            get {
                return ResourceManager.GetString("StakeDistribution_MA7Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoS Reward Distribution - A 3 day view of denom staking performance.
        /// </summary>
        public static string StakeDistribution_MetaDescription {
            get {
                return ResourceManager.GetString("StakeDistribution_MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOVING AVERAGE - X BLOCKS.
        /// </summary>
        public static string StakeDistribution_MovingAverage {
            get {
                return ResourceManager.GetString("StakeDistribution_MovingAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Blocks Staked by Denom.
        /// </summary>
        public static string StakeDistribution_NumberBlocksStakedDenom {
            get {
                return ResourceManager.GetString("StakeDistribution_NumberBlocksStakedDenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of PoS Blocks = Count of PoS over the last X blocks.
        /// </summary>
        public static string StakeDistribution_NumberOfPosFn {
            get {
                return ResourceManager.GetString("StakeDistribution_NumberOfPosFn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Blocks Staked by Denom = Count of block the selected denom staked over the last X blocks.
        /// </summary>
        public static string StakeDistribution_NumberOfStakedFn {
            get {
                return ResourceManager.GetString("StakeDistribution_NumberOfStakedFn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of PoS Blocks.
        /// </summary>
        public static string StakeDistribution_NumberPoSBlocks {
            get {
                return ResourceManager.GetString("StakeDistribution_NumberPoSBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoS Reward Distribution.
        /// </summary>
        public static string StakeDistribution_PageTitle {
            get {
                return ResourceManager.GetString("StakeDistribution_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REWARD CALCULATION.
        /// </summary>
        public static string StakeDistribution_RewardCalculation {
            get {
                return ResourceManager.GetString("StakeDistribution_RewardCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPPLY CALCULATION.
        /// </summary>
        public static string StakeDistribution_SupplyCalculation {
            get {
                return ResourceManager.GetString("StakeDistribution_SupplyCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Supply.
        /// </summary>
        public static string StakeDistribution_TotalSupply {
            get {
                return ResourceManager.GetString("StakeDistribution_TotalSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Supply = Average zerocoin supply over the last X blocks.
        /// </summary>
        public static string StakeDistribution_TotalSupplyFn {
            get {
                return ResourceManager.GetString("StakeDistribution_TotalSupplyFn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string StakeRoi_Daily {
            get {
                return ResourceManager.GetString("StakeRoi_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily PoS blocks.
        /// </summary>
        public static string StakeRoi_DailyPosBlocks {
            get {
                return ResourceManager.GetString("StakeRoi_DailyPosBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated:.
        /// </summary>
        public static string StakeRoi_LastUpdated {
            get {
                return ResourceManager.GetString("StakeRoi_LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoS reward frequency estimation.
        /// </summary>
        public static string StakeRoi_MainHeading {
            get {
                return ResourceManager.GetString("StakeRoi_MainHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string StakeRoi_Monthly {
            get {
                return ResourceManager.GetString("StakeRoi_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information.
        /// </summary>
        public static string StakeRoi_MoreInformation {
            get {
                return ResourceManager.GetString("StakeRoi_MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stake ROI assumptions.
        /// </summary>
        public static string StakeRoi_StakeAssumptions {
            get {
                return ResourceManager.GetString("StakeRoi_StakeAssumptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-end consumer CPU.
        /// </summary>
        public static string StakeRoi_StakeAssumptions1 {
            get {
                return ResourceManager.GetString("StakeRoi_StakeAssumptions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSD or NVMe storage drive.
        /// </summary>
        public static string StakeRoi_StakeAssumptions2 {
            get {
                return ResourceManager.GetString("StakeRoi_StakeAssumptions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Significant available RAM.
        /// </summary>
        public static string StakeRoi_StakeAssumptions3 {
            get {
                return ResourceManager.GetString("StakeRoi_StakeAssumptions3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-speed internet.
        /// </summary>
        public static string StakeRoi_StakeAssumptions4 {
            get {
                return ResourceManager.GetString("StakeRoi_StakeAssumptions4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very low latency.
        /// </summary>
        public static string StakeRoi_StakeAssumptions5 {
            get {
                return ResourceManager.GetString("StakeRoi_StakeAssumptions5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet open, unlocked, and staking active 24/7.
        /// </summary>
        public static string StakeRoi_StakeAssumptions6 {
            get {
                return ResourceManager.GetString("StakeRoi_StakeAssumptions6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the end luck is a factor!.
        /// </summary>
        public static string StakeRoi_StakeAssumptions7 {
            get {
                return ResourceManager.GetString("StakeRoi_StakeAssumptions7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total zerocoins.
        /// </summary>
        public static string StakeRoi_TotalZerocoins {
            get {
                return ResourceManager.GetString("StakeRoi_TotalZerocoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string StakeRoi_Weekly {
            get {
                return ResourceManager.GetString("StakeRoi_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which denominations are best? Check here.
        /// </summary>
        public static string StakeRoi_WhichDenomsBest {
            get {
                return ResourceManager.GetString("StakeRoi_WhichDenomsBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180 Days.
        /// </summary>
        public static string Transactions_180Days {
            get {
                return ResourceManager.GetString("Transactions_180Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 Days.
        /// </summary>
        public static string Transactions_30Days {
            get {
                return ResourceManager.GetString("Transactions_30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 Days.
        /// </summary>
        public static string Transactions_60Days {
            get {
                return ResourceManager.GetString("Transactions_60Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 Days.
        /// </summary>
        public static string Transactions_7Days {
            get {
                return ResourceManager.GetString("Transactions_7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90 Days.
        /// </summary>
        public static string Transactions_90Days {
            get {
                return ResourceManager.GetString("Transactions_90Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOCK TRANSACTIONS.
        /// </summary>
        public static string Transactions_BlockTransactions {
            get {
                return ResourceManager.GetString("Transactions_BlockTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction counts on the Veil network.
        /// </summary>
        public static string Transactions_MetaDescription {
            get {
                return ResourceManager.GetString("Transactions_MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated:.
        /// </summary>
        public static string Transactions_PageSubTitle {
            get {
                return ResourceManager.GetString("Transactions_PageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAILY TRANSACTIONS.
        /// </summary>
        public static string Transactions_PageTitle {
            get {
                return ResourceManager.GetString("Transactions_PageTitle", resourceCulture);
            }
        }
    }
}
